
#General settings
[gameruleconfig]

	[gameruleconfig.default]
		#Default value for this gamerule
		doFireTick = false
		#Default value for this gamerule
		#Range: 0 ~ 999999999
		maxCommandChainLength = 65536
		#Default value for this gamerule
		fireDamage = true
		#Default value for this gamerule
		reducedDebugInfo = false
		#Default value for this gamerule
		disableElytraMovementCheck = true
		#Default value for this gamerule
		announceAdvancements = true
		#Default value for this gamerule
		drowningDamage = true
		#Default value for this gamerule
		commandBlockOutput = true
		#Default value for this gamerule
		doMobSpawning = true
		#Default value for this gamerule
		#Range: 0 ~ 999999999
		maxEntityCramming = 24
		#Default value for this gamerule
		disableRaids = false
		#Default value for this gamerule
		doWeatherCycle = true
		#Default value for this gamerule
		doDaylightCycle = true
		#Default value for this gamerule
		showDeathMessages = true
		#Default value for this gamerule
		doTileDrops = true
		#Default value for this gamerule
		doInsomnia = true
		#Default value for this gamerule
		doImmediateRespawn = false
		#Default value for this gamerule
		naturalRegeneration = true
		#Default value for this gamerule
		doMobLoot = true
		#Default value for this gamerule
		fallDamage = true
		#Default value for this gamerule
		keepInventory = false
		#Default value for this gamerule
		doEntityDrops = true
		#Default value for this gamerule
		doLimitedCrafting = false
		#Default value for this gamerule
		mobGriefing = false
		#Default value for this gamerule
		#Range: 0 ~ 999999999
		randomTickSpeed = 3
		#Default value for this gamerule
		#Range: 0 ~ 999999999
		spawnRadius = 10
		#Default value for this gamerule
		doTraderSpawning = true
		#Default value for this gamerule
		logAdminCommands = false
		#Default value for this gamerule
		spectatorsGenerateChunks = false
		#Default value for this gamerule
		sendCommandFeedback = true
		#Default value for this gamerule
		doPatrolSpawning = true

	[gameruleconfig.change]

		[gameruleconfig.change.mobGriefing]
			#If the mobGriefing gamerule is false and this is true, it will allow ravagers (in the raids) to bypass gamerule and affect the world.
			ravager = false
			#If the mobGriefing gamerule is false and this is true, it will allow villagers (farming) to bypass gamerule and affect the world.
			villager = true
			#If the mobGriefing gamerule is false and this is true, it will allow snow golems to bypass gamerule and affect the world.
			snowgolem = true
			#If the mobGriefing gamerule is false and this is true, it will allow foxes eating berries to bypass gamerule and affect the world.
			fox = true
			#If the mobGriefing gamerule is false and this is true, it will allow blaze (projectiles / setting fire) to bypass gamerule and affect the world.
			blaze = true
			#If the mobGriefing gamerule is false and this is true, it will allow rabbits to bypass gamerule and affect the world (for example, raiding carrot farms and eating them).
			rabbit = true
			#If the mobGriefing gamerule is false and this is true, it will allow silverfish (entering stone to make infected stone) to bypass gamerule and affect the world.
			silverfish = true
			#If the mobGriefing gamerule is false and this is true, it will allow zombies to bypass gamerule and affect the world (for example doors, turtle eggs).
			zombie = true
			#If the mobGriefing gamerule is false and this is true, it will allow wither and projectiles to bypass gamerule and affect the world.
			wither = false
			#If the mobGriefing gamerule is false and this is true, it will allow ghasts projectiles to bypass gamerule and affect the world.
			ghast = false
			#If the mobGriefing gamerule is false and this is true, it will allow creeper explosions to bypass gamerule and affect the world.
			creeper = false
			#If the mobGriefing gamerule is false and this is true, it will allow sheep (eating grass) to bypass gamerule and affect the world.
			sheep = true
			#If the mobGriefing gamerule is false and this is true, it will allow enderman block pickup to bypass gamerule and affect the world.
			enderman = false

		[gameruleconfig.change.keepInventory]
			#If the keepInventory gamerule is true and keepArmor is false, you no longer keep any armor it dropped on death.
			keepArmor = false
			#If the keepInventory gamerule is true and keepArmor is false, you no longer keep any armor it dropped on death.
			keepWeapons = false
			#If the keepInventory gamerule is true and keepExperience is false, you no longer keep any experience it is gone on death.
			keepExperience = false

