#With this you can't see portal-in-portal
compatibility_render_mode = false
#With this the performance may drop
check_gl_error = false
#Max Portal-in-portal Render Layer
#Range: 1 ~ 10
max_portal_layer = 5
#Render Yourself In Portal
render_yourself_in_portal = true

