
#LanguageEnum settings
[language]
	#LanguageEnum locale the mod uses to check your chat messages. [default: EN_US]
	#Allowed Values: DA_DK, DE_CH, DE_DE, EN_GB, EN_US, ES_ES, FR_FR, IT_IT, NL_NL, NO_NO
	language_to_check = "EN_US"

#Checking settings
[checking]
	#The threshold the mod uses to check how close a word needs to be to the wrongly spelled word. [default: 0]
	#Range: > 0
	checking_threshold = 0

#General settings
[general]
	#The maximum number of suggestions it will show you. [default: 4]
	#Range: 1 ~ 20
	max_suggestions = 0

